# **Feature Engineering Notebook**
In this notebook, I will be doing feature engineering and introduce new features as required to help my model train better.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [8]:
from os import path
path_train = '/content/drive/MyDrive/Colab_Notebooks/predictive_maintenance_engine/data/raw/train_FD001.txt'
path_test = '/content/drive/MyDrive/Colab_Notebooks/predictive_maintenance_engine/data/raw/test_FD001.txt'
path_rul = '/content/drive/MyDrive/Colab_Notebooks/predictive_maintenance_engine/data/raw/RUL_FD001.txt'

In [5]:
columns = ['engine_id', 'cycle']
columns += [f'operational_setting_{i}' for i in range(1,4)]
columns += [f'sensors_{i}' for i in range(1,22)]

In [9]:
train_df_fd001 = pd.read_csv(path_train, sep = '\s+', header = None, names = columns)
test_df_fd001 = pd.read_csv(path_test, sep = '\s+', header = None, names = columns)
RUL_df_fd001 = pd.read_csv(path_rul, sep = '\s+', header = None, names = ['RUL'])

In [12]:
train_df_fd001.head()

,engine_id,cycle,operational_setting_1,operational_setting_2,operational_setting_3,sensors_1,sensors_2,sensors_3,sensors_4,sensors_5,...,sensors_12,sensors_13,sensors_14,sensors_15,sensors_16,sensors_17,sensors_18,sensors_19,sensors_20,sensors_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [13]:
test_df_fd001.head()

,engine_id,cycle,operational_setting_1,operational_setting_2,operational_setting_3,sensors_1,sensors_2,sensors_3,sensors_4,sensors_5,...,sensors_12,sensors_13,sensors_14,sensors_15,sensors_16,sensors_17,sensors_18,sensors_19,sensors_20,sensors_21
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130

In [14]:
RUL_df_fd001.head()

   RUL
0  112
1   98
2   69
3   82
4   91

In [19]:
engine_lifetime = train_df_fd001.groupby('engine_id')['cycle'].max()

In [20]:
# Vectorization concept
train_df_fd001['RUL'] = train_df_fd001['engine_id'].map(engine_lifetime) - train_df_fd001['cycle']
train_df_fd001.head()

,engine_id,cycle,operational_setting_1,operational_setting_2,operational_setting_3,sensors_1,sensors_2,sensors_3,sensors_4,sensors_5,...,sensors_13,sensors_14,sensors_15,sensors_16,sensors_17,sensors_18,sensors_19,sensors_20,sensors_21,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,191
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,190
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,189
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,188
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,187

In [21]:
# Piecewise RUL
train_df_fd001['RUL'] = train_df_fd001['RUL'].clip(upper=125)
train_df_fd001.head()

,engine_id,cycle,operational_setting_1,operational_setting_2,operational_setting_3,sensors_1,sensors_2,sensors_3,sensors_4,sensors_5,...,sensors_13,sensors_14,sensors_15,sensors_16,sensors_17,sensors_18,sensors_19,sensors_20,sensors_21,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,125
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,125
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,125
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,125
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,125

In [ ]:
# From previous EDA notebook
useful_sensors = ['sensors_2','sensors_3','sensors_4','sensors_7','sensors_8','sensors_9',
                  'sensors_11','sensors_12','sensors_13','sensors_14','sensors_15',
                  'sensors_17','sensors_20','sensors_21']

dropped_sensors = ['sensors_1','sensors_5','sensors_6','sensors_10','sensors_16',
                   'sensors_18','sensors_19']

op_settings = ['operational_setting_1','operational_setting_2','operational_setting_3']